### ISSUE TITLE
recovery from lost contiv-etcd

### ISSUE THREAD

**Issue by LipingMao** [contiv/vpp#1491] opened 2019-03-29 13:03 UTC
Hi Team,

When I do DR test for contiv-vpp etcd, I find if I delete contiv-etcd-0 pod, the data can be regenerated, but the POD-CIDR maybe mis-match with existed POD-CIDR.  In this case, I can recovery the pods network by delete them.

Is it possible for VPP to recovery with the original POD-CIDR?

**Comment by rastislavszabo** [comment] 2019-07-23 06:49
Duplicate of https://github.com/contiv/vpp/issues/1492

**Closed by rastislavszabo** 2019-07-23 06:49 UTC
Labels: duplicate
